### ISSUE TITLE
estados

### ISSUE THREAD

**Issue by czariv** [LucasLJG/e-commerce#1]
não é pra descrição do enum estado ser o nome do estado ao invés da capital?

**Comment by LucasLJG** [comment]
Não necessariamente, porque a gente já tem os enuns com os nomes dos Estados do Brasil, então eu pensei em adicionar como informação adicional na descrição os nomes das Capitais do Estados, porque repetir o nome do Estado de novo dentro da descrição fica redundante nesse caso.

**Comment by czariv** [comment]
Não ficaria redundante porque não da pra se acessar o nome do enum associado, no caso de vc mandar printar por exemplo

**Comment by czariv** [comment]
Eu acho que esse negocio da capital n faz sentido ter no enum tmb, já que vai associar o estado com um cliente n faz sentido ter essa informação, outra coisa é que a gente podia botar um numero diferente de parâmetros nessa enum do que q do lab pra ficar diferente

**Comment by LucasLJG** [comment]
Beleza, então se você já tiver outras ideias sobre essa enum e quiser implementar e alterar o que eu deixei fica a vontade.
