### ISSUE TITLE
Classe main

### ISSUE THREAD

**Issue by czariv** [LucasLJG/e-commerce#4]
Acho que encontrei um erro na main, quando não cadastramos nenhum usuário somos apresentados com uma tela para alteração do único usuário cadastrado, depois de teoricamente mudar a senha que se checa a autenticidade de quem esta tentando mudar a senha, não sei se isso é intencional mas parece muito estranho.
![a](https://user-images.githubusercontent.com/68134220/102051697-be90a680-3dc3-11eb-95bd-0c37d3b08ac0.png)

**Comment by czariv** [comment]
outra coisa eu vou mudar a classe Usuário porque esse "endereço de e-mail invalido" esta sendo exibido desnecessariamente

**Comment by LucasLJG** [comment]
Certo, fiz outras modificações na função alterar_senha e recuperar_senha. Na função de alterar_senha melhorei a segurança do sistema adicionando uma camada a mais de proteção que é o cpf do usuário que é pedido, antes de trocar a senha.
