### ISSUE TITLE
Erro em imput na main

### ISSUE THREAD

**Issue by czariv** [LucasLJG/e-commerce#5]
Ao selecionar um produto o programa espera um int e qualquer input diferente leva a um erro, não sei se precisamos abordar essa situação.
![ba](https://user-images.githubusercontent.com/68134220/102054742-98b9d080-3dc8-11eb-9a71-0e8eae427ae9.png)

**Comment by czariv** [comment]
esse erro ocorre devido ao comando **Integer.parseInt(leitor.nextLine())** e portanto se repete em vários locais da main, resolve-lo não deve ser difícil somente demorado, se vocês quiserem em posso tentar resolver isso, mas como disse não sei se é necessário abordar isso

**Comment by LucasLJG** [comment]
Já foi consertado esse problema. Obrigado por avisar!
